### ISSUE TITLE
Crashes frequently - client index is invalid

### ISSUE THREAD

**Issue by phorcep** [Rainyan/sourcemod-nt-teambalancer#1]
Mostly with this:

```
[SM] Native "IsClientConnected" reported: Client index ########## is invalid
[SM] Displaying call stack trace for plugin "neottb.smx":
[SM]   [0]  Line 536, neottb.sp::IsValidClient()
[SM]   [1]  Line 190, neottb.sp::Event_TeamBalanceThread()
```

Occurrences going back to 2010:  http://sprunge.us/igHb

**Comment by Rainyan** [comment]
Should hopefully be fixed in 8e62369

**Comment by Rainyan** [comment]
This seems to still be happening, no idea why yet. Gonna look into it more once I have the time

**Comment by softashell** [comment]
I'm using it on my server with IsValidClient from my include which seems to work with no problems

https://github.com/softashell/sourcemod-nt-include/blob/master/scripting/include/neotokyo.inc#L259

**Comment by Rainyan** [comment]
Alright, I added some debug logging to Creamy's version in hopes of catching what's wrong. Let me know if you still get that error, I guess the simple fix would be using your include if it does indeed work

**Comment by softashell** [comment]
Don't have to pull in all of it for that, just change the 1 > client > MaxClients to use || and it should work fine. There's something wrong with how sourcemod handles that.

**Comment by Rainyan** [comment]
Seems to be the case. Perhaps it evaluates the statement as a whole instead of working left-to-right through the conditions individually.

1 > 0 > 24 = false
0 < 1 || 0 > 24 = true

1 > 25 > 24 = false
25 < 1 || 25 > 24 = true

**Comment by Rainyan** [comment]
Hopefully fixed for good now, thanks
